server:
  port: 12350

spring:
  datasource:
    testdb:
      url: jdbc:mysql://localhost:3306/testdb?
      username: root
      password: welcome
    testdb2:
      url: jdbc:mysql://localhost:3306/testdb2?
      username: root
      password: welcome